###[POST] pay 추가
POST http://localhost:4000/pay
Content-Type: application/json

{
  "amount": 100
}


###[POST] order 추가
POST http://localhost:4000/order/add/1326
Content-Type: application/json

[
  { "name": "김치찌개", "count": 2 },
  { "name": "된장찌개", "count": 3 }
]


###[POST] order 추가
POST http://localhost:4000/order/add/1235
Content-Type: application/json

[
  { "Name": "김치찌개", "Count": 2 },
  { "Name": "된장찌개", "Count": 3 }
]


###[GET] order 불러오기 (주문 번호)
GET http://localhost:4000/order/get/1324

###[GET] order complete하기 (주문 번호)
GET http://localhost:4000/order/complete/set/102

###[GET] order 불러오기 (전체)
GET http://localhost:4000/order/get

###[GET] order id 불러오기 (전체)
GET http://localhost:4000/order/getid

###[GET] complete order id 불러오기 (전체)
GET http://localhost:4000/order/complete/getid

###[GET] complete 추가 (주문 번호)
GET http://localhost:4000/order/complete/set/101

###[POST] counter ordering order 추가
POST http://localhost:4000/pay/counter
Content-Type: application/json

{
  "orders":
  [
    { "Name": "김치찌개", "Count": 2 },
    { "Name": "된장찌개", "Count": 3 }
  ],
  "amount": 3000
}


###[GET] pay 완료하기 (주문 번호)
GET http://localhost:4000/pay/complete/101

###[GET] 가격 확인 (주문 번호)
GET http://localhost:4000/pay/amount/101